---
title: "Structural Bioinformatics: Exercise 2"
format:
  html:
    embed-resources: true
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: true
    number-sections: true
    number-depth: 3
    code-links:
      - text: "GitHub Repository"
        icon: github
        href: https://github.com/MCML-Projects/STRBIO_P2.git
authors: "Marta Aransay, Carlota de la Concepción, Marta Rodrigo, Lucía Santos"
date: 03/10/2026
bibliography: bibliografia.bib
csl: vancouver.csl  
---

# Goal of the project

This is a CASP-like exercise. The objective of this contest is to achieve the best possible predicted structure for at least three sequences using state-of-the-art protein modeling methodologies. For each sequence, you must utilize three or more different protocols for model generation and select the most optimal model.

# Background information of the selected proteins

{{< include docs/Protein1_bg.qmd >}}
{{< include docs/Protein2_bg.qmd >}}
{{< include docs/Protein3_bg.qmd >}}

# Protein modeling

## Protein 1: ORAI1

{{< include docs/Protein1_1Dfeatures.qmd >}}
{{< include docs/Protein1_complete.qmd >}}
{{< include docs/Protein1_evaluation.qmd >}}

## Protein 2

{{< include docs/Protein2_1Dfeatures.qmd >}}
{{< include docs/Protein2_complete.qmd >}}
{{< include docs/Protein2_evaluation.qmd >}}

## Protein 3: Osm1

{{< include docs/Protein3_1Dfeatures.qmd >}}
{{< include docs/Protein3_complete.qmd >}}
{{< include docs/Protein3_evaluation.qmd >}}

# Conclusion

Across the three proteins analyzed in this study, AlphaFold3 was consistently selected as the primary structural model, despite the different methodological approaches used for structure generation and prediction. Although AF3 operates as a “black box” with proprietary architectural constraints, its predictive performance offers clear advantages for future structural biology workflows. This is particularly evident in its ability to incorporate biologically relevant information, such as post-translational modifications (PTMs) in Protein 3, or the inclusion of essential ions required for protein function, as observed for Proteins 1 and 2.

In other words, the predictive accuracy of AlphaFold3 improves substantially when all available biological information is provided, for example the presence of phosphate groups in the monomer of the third sequence or other functionally relevant structural components.

However, other computational approaches demonstrated high predictive accuracy as well:
For Protein 1 (ORAI1), Swiss-Model yielded highly robust results. Due to the availability of high-identity templates, template-based homology modeling provided an exceptionally accurate representation of the protein’s native fold.

In the case of Protein 2, modeling within the "Twilight Zone" (low sequence identity, typically below 25-30%) presented significant challenges for traditional methods. Consequently, both ESMFold and AlphaFold 2 achieved superior structural accuracy, overcoming the limitations of template dependency to reach optimal stereochemical refinement. 

FIX ME - Carlota, no se si ponerlo aqui porque nos ha puesto discusion pero realmente de las demás tampooc hemos puesto potencial biotec:*Regarding the potential of Protein 2, protein engineering could reveal novel properties within this structural class. Its utility may be inferred by analyzing homologous structures and their respective biological functions*

For Protein 3, MODELLER produced high-quality results; however, it was not the final selection. The stability and biological relevance of the model could potentially be enhanced by the incorporation of PTMs and template optimization (more selective subset of templates to reduce structural noise).

Although the models predicted by AF3 showed high accuracy, these hypotheses require experimental validation (such as Cryo-EM) to confirm the structures. Furthermore, template-dependent analysis could bias the results toward specific conformational states (which might represent inactive forms).

Taken together, these results highlight the overall robustness of AlphaFold3 while also demonstrating that classical and hybrid modeling approaches can still provide highly reliable structural predictions depending on the availability of templates and the complexity of the target protein.

# References