---
title: 1D Features
format:
  html:
    embed-resources: true
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: true
    number-sections: true
authors: "Marta Aransay, Carlota de la Concepción, Marta Rodrigo, Lucía Santos"<
date: 10/03/2026
---

## Protein 3

The primary sequence of MoHog1/MoOsm1 (357 aa) exhibits the classic architecture of a MAP kinase. The catalytic domain (residues 23-311) contains all the conserved motifs necessary for phosphotransferase activity. Notably, the activation loop features the TGY motif (T171/Y173), characteristic of the stress-activated protein kinase (SAPK) family (Dixon et al., 1999, Liu et al., 2020). The activation of this motif through dual phosphorylation has been experimentally validated under osmotic and oxidative stress conditions, as well as in response to fungicide exposure (Motoyama et al., 2008). 

Building upon previous structural studies of p38 MAPKs, which demonstrated the formation of dimers through the swapping of activation segments (Rothweiler et al., 2011), the oligomeric state of MoOsm1 was experimentally evaluated. Functional assays confirmed that MoHog1/MoOsm1 exists in both monomeric and dimeric forms. However, the ability to dimerize is strictly regulated by the phosphorylation state of the activation loop. Specific point mutations which mimic different phosphorylation states shows that phosphorilation on Tyr173 serves as a molecular switch that inhibits the dimerization, the simulated phosphorilation on T171 does not shown any effect on dimerization. These findings imply that *in silico* phosphorylation on Tyr173 of the MoHog1/MoOsm1 dimer would likely result in steric clashes or significant conformational instability. Since the phosphorylated state (simulated by the Y173D mutation) prevents dimerization *in vivo*, any structural model attempting to force a phosphorylated activation loop into a dimeric interface would likely exhibit an energetically unfavorable or distorted geometry. 


Rothweiler et al., 2011 -> https://doi.org/10.1016/j.jmb.2011.06.013 

Liu et al., 2020 -> https://doi.org/10.7554/eLife.61605 

https://doi.org/10.3390/biology14111545

Zhang, H., Yang, J., Liu, M. et al. Early molecular events in the interaction between Magnaporthe oryzae and rice. Phytopathol Res 6, 9 (2024). https://doi.org/10.1186/s42483-024-00226-z

Motoyama, T., Ochiai, N., Morita, M. et al. Involvement of putative response regulator genes of the rice blast fungus Magnaporthe oryzae in osmotic stress response, fungicide action, and pathogenicity. Curr Genet 54, 185–195 (2008). https://doi.org/10.1007/s00294-008-0211-0