<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>protein3_complete</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Protein3_complete_files/libs/clipboard/clipboard.min.js"></script>
<script src="Protein3_complete_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Protein3_complete_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Protein3_complete_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Protein3_complete_files/libs/quarto-html/popper.min.js"></script>
<script src="Protein3_complete_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Protein3_complete_files/libs/quarto-html/anchor.min.js"></script>
<link href="Protein3_complete_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Protein3_complete_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Protein3_complete_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Protein3_complete_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Protein3_complete_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The sequence used to model MoOsm1/MoHog1 is:</p>
<p><strong>sp|Q9UV51|HOG1_PYRO7 Mitogen-activated protein kinase HOG1</strong> OS=Pyricularia oryzae (strain 70-15 / ATCC MYA-4617 / FGSC 8958) OX=242507 GN=HOG1 PE=1 SV=1</p>
<p>MAEFVRAQIFGTTFEITSRYSDLQPVGMGAFGLVCSARDQLTNQNVAIKKIMKPFSTPVLAKRTYRELKLLKHLKHENVISLSDIFISPLEDIYFVTELLGTDLHRLLTSRPLEKQFIQYFLYQIMRGLKYVHSAGVVHRDLKPSNILVNENCDLKICDFGLARIQDPQMTGYVSTRYYRAPEIMLTWQKYDVEVDIWSAGCIFAEMLEGKPLFPGKDHVNQFSIITELLGTPPDDVINTIASENTLRFVKSLPKRERQPLKNKFKNADPSAIDLLERMLVFDPKKRITATEALAHEYLTPYHDPTDEPIAEEKFDWSFNDADLPVDTWKIMMYSEILDYHNAEAGMQQMDDQFTGQ</p>
</div>
</div>
<p>To capture the dual nature of MoHog1—which alternates between a monomeric inactive state and a dimeric active state regulated by Y173 phosphorylation—a multi-platform approach was employed. AlphaFold 3 was selected for its superior accuracy in predicting the activation loop’s local environment, while Modeller allowed for template-driven constraints to explore the monomeric interface based on experimental homologs. I-TASSER was selected due to its hybrid methodology, which combines threading and ab initio modeling. Furthermore, I-TASSER was also employed to determine solvent accessibility (ASA), providing a comparative baseline against NetSurfP-3.0 result.</p>
<section id="deep-learning-alphafold3" class="level3">
<h3 class="anchored" data-anchor-id="deep-learning-alphafold3">Deep Learning (AlphaFold3)</h3>
<p>Although the structural analysis could have been performed using AlphaFold 2 by employing phosphomimetic mutations—such as the Y173D substitution used in in vivo experiments to demonstrate the impact of phosphorylation—this approach has inherent limitations. While aspartic acid partially mimics the negative charge of a phosphorylated tyrosine, it remains a surrogate that does not fully capture the specific steric and chemical properties of a true phosphate group. Consequently, AlphaFold 3 was selected for this study, as it has been specifically trained on datasets containing Post-Translational Modifications (PTMs). This allows for a more biophysically accurate representation of the monomeric state of MoOsm1, providing deeper insights into the precise structural hindrances and conformational changes triggered by actual phosphorylation at the Y173 position.</p>
<p>Consequently, both states were modeled. Analysis of these models reveals two key structural requirements that must be met. First, in the unphosphorylated monomer, the activation site must be solvent-accessible to allow the upstream kinase to perform the phosphorylation. Additionally, in the unphosphorylated dimer, the TGY motif is expected to be buried within the complex interface, specifically at the protein-protein interaction site. This configuration explains why phosphorylation at this position prevents dimerization, as the addition of bulky, negatively charged phosphate groups would physically and energetically disrupt the assembly of the dimeric interface.</p>
<section id="methods" class="level4">
<h4 class="anchored" data-anchor-id="methods"><strong>Methods</strong></h4>
<p>Using the <a href="https://alphafoldserver.com/">AlphaFold3 server</a>, as previously detailed, structural modeling was performed for both the monomeric (<code>copies: 1</code>) and dimeric (<code>copies: 2</code>) states of the MoOsm1/MoHog1 protein. In all generated models, phosphorylation at Threonine 171 (T171) was maintained as a constant modification. Additionally, both the monomer and the dimer were modeled with and without the phosphorylation at Tyrosine 173 (Y173)(<a href="#fig-params-AFServer-Osm1" class="quarto-xref">Figure&nbsp;1</a>). While the phosphorylated dimeric state does not occur naturally in vivo, it was explicitly modeled to analyze how this specific post-translational modification (PTM) affects the structural integrity and regulation of the complex.</p>
<p>This approach allows for a precise characterization of the conformational shifts and potential steric clashes induced by the addition of phosphate groups in the activation loop. Specifically, the phosphorylated dimer model was generated to examine the steric hindrance caused by the phosphate group at Y173, which is known to prevent stable dimerization. Conversely, the unphosphorylated monomer (at Y173) was modeled to establish the baseline localization of the TGY motif in its basal, yet T171-phosphorylated, state.</p>
<div id="fig-params-AFServer-Osm1" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-params-AFServer-Osm1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-params-AFServer-Osm1" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-params-Osm1-AF3monomer1P" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-params-Osm1-AF3monomer1P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\pics/Protein3/ParamsAF3/Osm1_Monomer_171P.png" id="fig-params-Osm1-AF3monomer1P" data-ref-parent="fig-params-AFServer-Osm1" height="250" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-params-Osm1-AF3monomer1P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-params-AFServer-Osm1" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-params-Osm1-AF3monomer2P" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-params-Osm1-AF3monomer2P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\pics/Protein3/ParamsAF3/Osm1_Monomer_BothP.png" id="fig-params-Osm1-AF3monomer2P" data-ref-parent="fig-params-AFServer-Osm1" height="250" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-params-Osm1-AF3monomer2P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-params-AFServer-Osm1" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-params-Osm1-AF3dimer1P" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-params-Osm1-AF3dimer1P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\pics/Protein3/ParamsAF3/Osm1_Dimer_171P.png" id="fig-params-Osm1-AF3dimer1P" data-ref-parent="fig-params-AFServer-Osm1" height="250" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-params-Osm1-AF3dimer1P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c)
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-params-AFServer-Osm1" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-params-Osm1-AF3dimer2P" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-params-Osm1-AF3dimer2P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src=".\pics/Protein3/ParamsAF3/Osm1_Dimer_BothP.png" id="fig-params-Osm1-AF3dimer2P" data-ref-parent="fig-params-AFServer-Osm1" height="250" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-params-Osm1-AF3dimer2P-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d)
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-params-AFServer-Osm1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: <strong>AlphaFold Server parameters selected for the structural modeling of MoOsm1 conformations.</strong> <strong>A.</strong> Parameters used for the pT171 mono-phosphorylated monomer. <strong>B.</strong> Parameters used for the pT171/pY173 dual-phosphorylated monomer. <strong>C.</strong> Parameters used for the pT171 mono-phosphorylated dimer. <strong>D.</strong> Parameters used for the pT171/pY173 dual-phosphorylated dimer.
</figcaption>
</figure>
</div>
<p>The structural consistency of the models generated by AF3 was evaluated by comparing the five independent ranked outputs for both the dual-phosphorylated monomer (pT171/pY173) and the phosphorylated dimer (pT171), using a Root Mean Square Deviation (RMSD) threshold of &lt; 1 Å to define high-confidence convergence.</p>
<p>To analyze the MoOsm1 structural models, a standardized PyMOL workflow was implemented, following the same evaluation protocol and modeling confidence standards established for the study of Protein 1 (ORAI1) (<strong>?@sec-prot1-methods</strong>).</p>
<p>The TGY activation motif was specifically isolated for detailed inspection by creating a dedicated selection: <code>select Osm1Mono_bothP_TGY, quarternarystate_PTMs and resi 171+173</code>. To facilitate structural analysis, these residues were rendered as sticks with <code>show sticks, Osm1Mono_bothP_TGY</code> and highlighted in <code>color red, Osm1Mono_bothP_TGY</code>. Furthermore, the phosphate groups were emphasized by rendering phosphorus atoms as spheres with <code>show spheres, (Osm1Mono_bothP_TGY and name P)</code> and a scale adjustment of <code>set sphere_scale, 0.3, (Osm1Mono_bothP_TGY and name P)</code>.</p>
<p>For publication-quality figure export, the following environment settings and high-resolution rendering commands were applied. The background was set to a neutral white using <code>bg_color white</code>, and shadows were disabled to enhance structural clarity with <code>set ray_shadows, 0</code>. Additionally, the visual representation of alpha-helices was refined through <code>set cartoon_fancy_helices, 1</code>. Finally, the images were generated using high-resolution ray-tracing with the command <code>ray 1200, 1200</code>.</p>
</section>
<section id="results" class="level4">
<h4 class="anchored" data-anchor-id="results"><strong>Results</strong></h4>
<p>The structural evaluation of MoOsm1 across different phosphorylation states shows that all models exceed the 0.5 threshold for the predicted Template Modeling (pTM) score, confirming that the global kinase fold was correctly predicted in all cases (<a href="#tbl-pTM" class="quarto-xref">Table&nbsp;2</a>). However, a significant disparity was observed in local confidence, the doubly phosphorylated monomer (Thr171P/Thr173P) achieved a near-native score of 0.87, whereas the other monomeric and dimeric variants yielded lower values ranging from 0.53 to 0.58 (<a href="#tbl-ipTM" class="quarto-xref">Table&nbsp;1</a>). Regarding the interface predicted Template Modeling (ipTM) scores, all results remained significantly below the 0.6 threshold. Specifically, the Monomer_171P variant returned a value of 0.18, identifying it as a computational artifact of the multimeric protocol, while the dimeric models reached only 0.22 and 0.19, indicating a lack of structural consistency in the predicted relative orientation of the subunits.</p>
<div id="tbl-ipTM" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipTM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Interface predicted Template Modeling (ipTM) scores for monomeric and dimeric MoOsm1 phosphorylation states.
</figcaption>
<div aria-describedby="tbl-ipTM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>ipTM</th>
<th>Monomer</th>
<th>Dimer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>171P</td>
<td>0.18</td>
<td>0.22</td>
</tr>
<tr class="even">
<td>171P/173P</td>
<td>-</td>
<td>0.19</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-pTM" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pTM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Predicted Template Modeling (pTM) scores for monomeric and dimeric MoOsm1 variants.
</figcaption>
<div aria-describedby="tbl-pTM-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>pTM</th>
<th>Monomer</th>
<th>Dimer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>171P</td>
<td>0.53</td>
<td>0.58</td>
</tr>
<tr class="even">
<td>171P/173P</td>
<td>0.87</td>
<td>0.53</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>For the dual-phosphorylated monomer (<span class="citation" data-cites="fig_P3_Osm1Mono_bothP_AFcolored">@fig_P3_Osm1Mono_bothP_AFcolored</span>), the alignments of the Osm1 monomer models 1 through 4 against the top-ranked model 0 exhibited a high degree of structural similarity in their conserved cores, with a mean refined RMSD of 0.37 Å (ranging from 0.28 Å to 0.45 Å). Out of the 2,905 total atoms in each model, an average of approximately 2,274 atoms were used for the final calculation.</p>
<div id="fig_P3_Osm1Mono_bothP_AFcolored" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src=".\pics/Protein3/Monomer_BothP/Osm1Mono_bothP_5models_aligned.png" class="img-fluid figure-img"></p>
<figcaption>Monomer structure modeled with AF3 visualization. The coloring color code follows next code: (Dark Blue, pLDDT &gt; 90; Light Blue/Cyan, 70 &lt; pLDDT &lt; 90; Yellow, 50 &lt; pLDDT &lt; 70; Orange, pLDDT &lt; 50)</figcaption>
</figure>
</div>
<p>The dimeric models (<span class="citation" data-cites="fig_P3_dimer_171P_AFcolored">@fig_P3_dimer_171P_AFcolored</span>) exhibited a bifurcated behavior in their structural convergence. While the alignments of models 1 and 2 against the top-ranked model 0 remained highly stable with an RMSD below 0.6 Å, models 3 and 4 showed an extreme displacement, reaching 28.99 Å and 29.55 Å, respectively. This disparity resulted in an overall mean refined RMSD of 14.91 Å, calculated from an average of 5,372 atoms out of the 5,802 total atoms in each dimeric model. This significant divergence in the lower-ranked models suggests a lack of conformational consensus in the dimeric interface.</p>
<div id="fig_P3_dimer_171P_AFcolored" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src=".\pics/Protein3/Dimer_171P/dimer_T171P_red.png.png" class="img-fluid figure-img"></p>
<figcaption>Dimer structure modeled with AF3 visualization. The coloring color code follows next code: Dark Blue, pLDDT &gt; 90; Light Blue/Cyan, 70 &lt; pLDDT &lt; 90; Yellow, 50 &lt; pLDDT &lt; 70; Orange/Red, pLDDT &lt; 50)</figcaption>
</figure>
</div>
<p>The top-ranked Model 0 was selected as the reference structure based on its superior convergence and global scoring. The key validation parameters, are summarized in <a href="#tbl-prot3-af3" class="quarto-xref">Table&nbsp;3</a>.</p>
<div id="tbl-prot3-af3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prot3-af3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Structural quality metrics obtained by AlphaFold3 for de monomer and the dimer.
</figcaption>
<div aria-describedby="tbl-prot3-af3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Monomer value</th>
<th>Dimer value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Ranking Score</strong></td>
<td>0.89</td>
<td>0.3</td>
</tr>
<tr class="even">
<td><strong>ipTM</strong></td>
<td>Null</td>
<td>0.22</td>
</tr>
<tr class="odd">
<td><strong>pTM</strong></td>
<td>0.87</td>
<td>0.55</td>
</tr>
<tr class="even">
<td><strong>Fraction Disordered</strong></td>
<td>0.04</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td><strong>Has Clash</strong></td>
<td>0.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td><strong>Recycles</strong></td>
<td>10.0</td>
<td>10.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>To analyze the effect of phosphorylation on the dimerization interface, the distance between specific residues across the chains was quantified. We employed the command <code>distance dist_171P, (Osm1Dimer_171P_0 and chain A and resi 171 and element P), (Osm1Dimer_171P_0 and chain B and resi 171 and element P)</code> to measure the inter-chain separation between the phosphorus atoms of residue 171. Similar measurements were performed for residue 173 by adjusting the residue index accordingly.</p>
<p>These calculations were applied to both dimeric states: the mono-phosphorylated dimer (pT171) and the dual-phosphorylated dimer (pT171/pY173). The resulting data, presented in <strong>?@tbl-distances-171P-173P</strong>, are expected to reveal a greater distance between residues 173 in the phosphorylated state compared to the non-phosphorylated state. Furthermore, if the distance between the pT171 residues is significantly higher in the dual-phosphorylated dimer, it would suggest that the presence of the phosphate group on residue 173 induces additional structural tension or steric repulsion at the dimeric interface.</p>
<p>–FIX ME si hay tiempo</p>
<div id="tbl-distances-171P-173" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-distances-171P-173-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Phosphorilated residues distance on dimer structures of the Osm1 modeled structure.
</figcaption>
<div aria-describedby="tbl-distances-171P-173-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 15%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th>Distance between residues of both chains</th>
<th>Osm1 Dimer 171P</th>
<th>Osm1 Dimer 171P and 173P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>171</strong></td>
<td>28.8</td>
<td>-</td>
</tr>
<tr class="even">
<td><strong>173</strong></td>
<td>24.8</td>
<td>-</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>–</p>
</section>
<section id="discussion" class="level4">
<h4 class="anchored" data-anchor-id="discussion"><strong>Discussion</strong></h4>
<p>In the first place, the pTM and ipTM scores collectively indicate that while the global kinase fold is consistently maintained, the local and interfacial stability varies significantly depending on the phosphorylation state. The high reliability of the Thr171P/Thr173P monomer suggests that the simultaneous presence of both phosphate groups acts as a critical stabilizing factor for the activation loop, likely supported by the availability of dually phosphorylated homologous templates in experimental databases. In contrast, the lower pTM values for the monophosphorylated monomer and the dimeric models reflect a higher degree of localized structural uncertainty. The slightly higher pTM of the monophosphorylated dimer (0.58) compared to the diphosphorylated versions suggests that the accumulation of four phosphate groups in the dimer may introduce electrostatic or steric instability that the model cannot resolve as a rigid complex. Consequently, while phosphorylation clearly stabilizes the monomeric activation loop, these computational results do not provide evidence that double phosphorylation enhances the stability of the dimeric interface beyond previously reported experimental observations, suggesting instead a highly dynamic or transient interaction.</p>
<p>The alignment of the models of the dual-phosphorylated monomer (<span class="citation" data-cites="fig_P3_Osm1Mono_bothP_AFcolored">@fig_P3_Osm1Mono_bothP_AFcolored</span>) indicates a highly robust and virtually identical conformational landscape across all iterations, suggesting a stable and well-defined fold for the activation loop in this state.</p>
<p>In contrast, the dimeric models (<span class="citation" data-cites="fig_P3_dimer_171P_AFcolored">@fig_P3_dimer_171P_AFcolored</span>) exhibited a significant structural deviation in the lower-ranked models. It suggests that, although the primary prediction for the dimer remains relatively stable, the overall modeling robustness is lower than that of the monomer. The 30 Å shift likely reflects a failure of the algorithm to consistently resolve the dimeric interface under the tension of the phosphate group, highlighting a higher degree of uncertainty or potential conformational instability in the dimeric assembly compared to the monomeric state.</p>
<p>Regarding the results obtained (<a href="#tbl-prot3-af3" class="quarto-xref">Table&nbsp;3</a>), the ranking score of 0.89 for the monomer indicates very high confidence in the predicted structure. In contrast, the dimer shows a much lower ranking score (0.30), suggesting that the overall prediction is significantly less robust in the oligomeric state. The pTM value of 0.87 for the monomer further supports the reliability of the global fold. In the same line, the ipTM value of 0.22 for the dimer indicates weak confidence in the predicted interface between the two subunits, suggesting that the inter-chain interactions are not consistently resolved by the algorithm. It is also noteworthy that the fraction of disordered residues is very low in both cases (0.04 for the monomer and 0.03 for the dimer), indicating that most of the structure is predicted to adopt a stable folded conformation. In addition, no steric clashes were detected in either model, confirming that the atomic geometry of the structures is physically plausible.</p>
</section>
</section>
<section id="i-tasser" class="level3">
<h3 class="anchored" data-anchor-id="i-tasser">I-Tasser</h3>
<section id="justification-of-the-method" class="level4">
<h4 class="anchored" data-anchor-id="justification-of-the-method">Justification of the method</h4>
<p><a href="https://aideepmed.com/I-TASSER/">I-TASSER</a> was selected for its robust fragment assembly approach guided by threading techniques, a methodology that enables the prediction of protein structures even when close homologs are limited (<span class="citation" data-cites="Zheng2021">@Zheng2021</span>, <span class="citation" data-cites="Zhang2017">@Zhang2017</span>, <span class="citation" data-cites="Yang2015">@Yang2015</span>). While more computationally intensive than AlphaFold, it offers significant advantages for enzymes like kinases due to its specialized modeling of active sites and functional domains. Furthermore, the integration of C-I-TASSER provides essential confidence scores and structural templates that validate the predicted models, making it a highly reliable tool for targets where precision in functional regions is critical</p>
<p>In the specific case of MoOsm1, although several experimentally resolved homologs exist, sequence identities generally hover around 40%. While this level is acceptable for classical homology modeling, a threading-based approach was employed to gain an independent structural perspective. By integrating fragment-based ab initio folding, I-TASSER can better resolve regions where evolutionary divergence might lead to local structural variations. Additionally, the detailed Multiple Sequence Alignment (MSA) provided during the threading process allows for verification of the conserved TGY motif across selected templates, ensuring the structural integrity of this critical functional domain in the final model.</p>
</section>
<section id="methods-1" class="level4">
<h4 class="anchored" data-anchor-id="methods-1"><strong>Methods</strong></h4>
<p>The structural modeling of the protein was conducted using the I-TASSER suite under its default parameters, allowing for an unbiased exploration of the conformational space. The process integrated LOMETS meta-threading for template identification with iterative Monte Carlo simulations for fragment assembly. By adhering to the server’s standardized protocols, the final models were refined through FG-MD and REMO, ensuring a high-confidence structural ensemble validated by their respective C-scores and estimated TM-scores.</p>
</section>
<section id="results-1" class="level4">
<h4 class="anchored" data-anchor-id="results-1"><strong>Results</strong></h4>
<p>The I-TASSER structural prediction for MoOsm1 yielded high-confidence results, particularly for the top two models. Model 2 exhibited the highest convergence (C-score = 0.44), closely followed by Model 1 (C-score = 0.35). The estimated TM-score of 0.76 ± 0.10 for the primary model confirms a high topological accuracy, significantly exceeding the 0.5 threshold for correct global folding. Given the sharp decline in confidence scores for Models 3 and 4, subsequent structural analysis was focused exclusively on the high-ranking models to ensure biological relevance.</p>
<p>The local reliability of I-TASSER structural models is represented by the ResQ (Residue-specific Quality) by providing a statistical estimation of the distance error (in Ångströms) for each residue relative to its native position(which is estimated based on model convergence, consistency with structural templates, and threading uncertainty). Therefore, low values indicate high precision and confidence, while high values signal regions of greater structural uncertainty. Given that the estimated local accuracy threshold in the ResQ plot (<strong>?@fig-pnorm-Bfactor-p3-1</strong>) is predominantly situated around 3 Å, this same value was established as the cutoff for the structural color-coding to ensure visual consistency between the quantitative graph and the 3D model.</p>
<p>Although ResQ and AlphaFold’s pLDDT are different metrics, a similar color scale has been implemented for visual consistency: marine (dark blue) represents the areas of highest reliability and orange indicates lower modeling quality (<strong>?@fig-pnorm-Bfactor-p3-2</strong>). To apply this representation in PyMOL, the following commands were used: <code>color marine, Itasser_model1</code>, <code>color lightteal, Itasser_model1 and b &gt; 3</code>, <code>color yellow, Itasser_model1 and b &gt; 5.5</code>, <code>color orange, Itasser_model1 and b &gt; 9</code>, and <code>color red, resi 171</code> to specifically highlight the position of interest.</p>
<p>The B-factor measures the inherent thermal mobility of residues, here reported as a normalized profile (<span class="math inline">\(B = (B' - \mu) / \sigma\)</span>) to identify regions of relative flexibility or stability throughout the protein sequence (<strong>?@fig-pnorm-Bfactor-p3-3</strong>).</p>
<div id="fig-pnorm-Bfactor-p3" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pnorm-Bfactor-p3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<img src=".\models/Hog1/S822579_results_Itasser/RSQ_1.png" id="fig-Itasser_ResQ_graph" height="250" class="figure-img">
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pnorm-Bfactor-p3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: <strong>Structural quality assessment of the MoOsm1 model</strong>. <strong>A</strong> Local accuracy profile generated by ResQ, showing the estimated distance error (Å) per residue. <strong>B</strong> Three-dimensional representation of the top-ranking I-TASSER model, color-coded by ResQ values to highlight regions of high (marine/lightteal) and low (orange) structural confidence. <strong>C</strong> Predicted normalized B-factor profile, indicating the relative vibrational motion and flexibility of each residue.
</figcaption>
</figure>
</div>
<p>##FIX ME faltaria la parte de cofactores y demás</p>
</section>
<section id="interpretation-of-results-discusion" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-results-discusion">Interpretation of results (discusion)</h4>
<p>The structural analysis of the MoOsm1 model, color-coded according to ResQ values, reveals a high-confidence catalytic core characterized by a predominance of marine and lightteal hues, indicating an estimated distance error below 3–4 Å and validating the precision of the global fold. While the kinase’s main body shows robust structural stability supported by model convergence and template consistency, peripheral regions such as the N-terminal tail and specific surface loops exhibit yellow and orange colors (with estimated errors &gt; 9 Å), reflecting greater statistical uncertainty due to the lack of rigid experimental templates in these intrinsically flexible areas. Residue 171, highlighted in red for its biological relevance, is located precisely within one of these transitional regions of lower local precision, which is consistent with its function in the activation loop where structural plasticity is required to accommodate conformational changes during phosphorylation events. Overall, the model’s reliability is confirmed by a C-score of 0.90 and an estimated TM-score of 0.84, placing this prediction in an excellent accuracy category despite the detected local quality variations.</p>
<p>The predicted normalized B-factor profile (<a href="#fig-pnorm-Bfactor-p3" class="quarto-xref">Figure&nbsp;2</a>) indicates high overall structural stability for the monomer, as evidenced by the prevalence of negative values throughout the chain. However, a detailed analysis of the 170–175 residue range reveals positive normalized B-factor values, indicating enhanced local flexibility. This observed mobility in the 171 and 173 positions is consistent with their biological role as key phosphorylation sites, where structural plasticity is required to accommodate the transition between different activation states</p>
</section>
</section>
<section id="modeller" class="level3">
<h3 class="anchored" data-anchor-id="modeller">Modeller</h3>
<section id="justification-of-the-method-1" class="level4">
<h4 class="anchored" data-anchor-id="justification-of-the-method-1">Justification of the method</h4>
<p>Due to the lack of an experimental structure for the target protein, the Modeller algorithm was selected for structural prediction.</p>
</section>
<section id="methods-2" class="level4">
<h4 class="anchored" data-anchor-id="methods-2">Methods</h4>
<p>To ensure the highest modeling accuracy, six high-quality templates were identified based on sequence similarity and high coverage, as detailed in <a href="#tbl-PDB-codes-homology" class="quarto-xref">Table&nbsp;5</a>. These templates correspond to X-ray diffraction-resolved structures from various organisms. To enhance alignment resolution and similarity detection, a specialized template search was conducted using two iterations of PSI-BLAST. The selection process strictly prioritized templates maintaining at least 50% Sequence Identity and a Query Coverage (QCoverage) exceeding 90%, ensuring a robust structural foundation for the homology modeling process.</p>
<p>. Como se ve en la tabla (<a href="#tbl-PDB-codes-homology" class="quarto-xref">Table&nbsp;5</a>):</p>
<div id="tbl-PDB-codes-homology" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-PDB-codes-homology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: PDB codes of homologous sequences of Osm1 sequence obtained by BlastP.
</figcaption>
<div aria-describedby="tbl-PDB-codes-homology-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">PDB code</th>
<th style="text-align: center;">% identity</th>
<th style="text-align: center;">% coverage</th>
<th style="text-align: center;">e-value</th>
<th style="text-align: center;">Organism</th>
<th style="text-align: center;">Resolution method</th>
<th style="text-align: center;">Resolution (Å)</th>
<th style="text-align: center;">TXY site presence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">3P5K</td>
<td style="text-align: center;">51.17 %</td>
<td style="text-align: center;">94 %</td>
<td style="text-align: center;">1e-136</td>
<td style="text-align: center;"><em>Mus musculus</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">2.09</td>
<td style="text-align: center;">TGY</td>
</tr>
<tr class="even">
<td style="text-align: center;">3K3I</td>
<td style="text-align: center;">51.17 %</td>
<td style="text-align: center;">94 %</td>
<td style="text-align: center;">5e-178</td>
<td style="text-align: center;"><em>Homo sapiens</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">1.70</td>
<td style="text-align: center;">TGY</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8H59</td>
<td style="text-align: center;">44.06 %</td>
<td style="text-align: center;">93 %</td>
<td style="text-align: center;">2e-185</td>
<td style="text-align: center;"><em>Magnaporthe oryzae</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">2.15</td>
<td style="text-align: center;">TEY</td>
</tr>
<tr class="even">
<td style="text-align: center;">7W5C</td>
<td style="text-align: center;">47.41 %</td>
<td style="text-align: center;">95 %</td>
<td style="text-align: center;">1e-173</td>
<td style="text-align: center;"><em>Arabidopsis thaliana</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">2.20</td>
<td style="text-align: center;">TEY</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6RFP</td>
<td style="text-align: center;">47.95 %</td>
<td style="text-align: center;">93 %</td>
<td style="text-align: center;">3e-167</td>
<td style="text-align: center;"><em>Rattus norvegicus</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">1.74</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: center;">2B9F</td>
<td style="text-align: center;">45.27 %</td>
<td style="text-align: center;">92 %</td>
<td style="text-align: center;">3e-154</td>
<td style="text-align: center;"><em>Saccharomyces cerevisiae</em></td>
<td style="text-align: center;">X-ray diffraction</td>
<td style="text-align: center;">1.80</td>
<td style="text-align: center;">TEY</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Subsequently, the structural data for the six selected templates—<a href="https://www.rcsb.org/structure/3P5K">3P5K</a>, <a href="https://www.rcsb.org/structure/3K3I">3K3I</a>, <a href="https://www.rcsb.org/structure/8H59">8H59</a>, <a href="https://www.rcsb.org/structure/7W5C">7W5C</a>, <a href="https://www.rcsb.org/structure/6RFP">6RFP</a>, <a href="https://www.rcsb.org/structure/2B9F">2B9F</a>—were retrieved from the RCSB PDB database using the ‘Fetch by ID’ tool in ChimeraX. To ensure a clean structural environment for modeling, all non-standard residues, including ligands and water molecules, were identified and deleted (Actions &gt; Atoms/Bonds &gt; Delete). A structural superposition was then performed using the Match-&gt;Align tool to achieve a preliminary spatial orientation of the templates.</p>
<p>The target sequence, MoHog1, was imported from a <em>.fasta</em> file and integrated into the alignment using the ‘Best-aligning pair of chains’ protocol. Within the Multalign Viewer, a sequence realignment was executed to optimize the residues’ positioning. Every template structure was then manually associated with its corresponding sequence in the alignment, ensuring that the MoHog1 sequence remained unassociated (‘None’) as the target for homology.</p>
<p>For the modeling phase, all six structures were selected as templates. The homology modeling was performed via the Modeller (homology) interface. Advanced configuration parameters were adjusted to define the total number of models to be generated, ensuring a robust sampling of the conformational space for the final MoHog1 structure.</p>
<p>The structural integrity of the best-ranking MoHog1 model was validated using the zDOPE (Discrete Optimized Protein Energy) score. The model achieved a zDOPE value of -1.45, which is significantly below the -1.0 threshold typically used to identify high-quality, native-like folds. This score confirms that the spatial arrangement of residues is energetically favorable and statistically consistent with experimental protein structures, further supporting the reliability of the homology modeling process.</p>
</section>
<section id="results-2" class="level4">
<h4 class="anchored" data-anchor-id="results-2">Results</h4>
<p>The structural integrity of the unphosphorylated MoHog1 monomer was validated through a comprehensive alignment against the six experimental templates used in the homology modeling process. The structural convergence was highly consistent across all templates, with Root Mean Square Deviation (RMSD) values ranging from 0.759 Å to 1.113 Å. Specifically, the closest structural proximity was observed with template 6RFP (0.759 Å over 1,743 atoms), while the maximum deviation was found with 3P5K (1.113 Å over 1,910 atoms). These low RMSD values, calculated over a significant fraction of the 2,897 total atoms in the predicted monomer, demonstrate a high degree of conformational conservation and confirm that the modeled kinase core strictly maintains the canonical architecture observed in homologous X-ray structures.</p>
<p>The structure is color-coded by transferred B-factors, ranging from cool tones (marine, B <span class="math inline">\(\approx\)</span> 25) to warm tones (orange, B <span class="math inline">\(\ge\)</span> 100). The visualization shows greater stability and a well-folded catalytic core (partially blue), which is consistent with the robust global zDOPE score of -1.45. In contrast, the activation loop (central region) appears prominently in orange, reflecting the exceptionally high transferred mobility observed in experimental templates (e.g., B=509.37 at Thr171). This graphical representation confirms that the orange-colored regions identify a site of high intrinsic flexibility, a structural feature necessary to facilitate the occurrence of phosphorylation events. The low rigidity observed in this area suggests that the activation loop is conformationally dynamic, which enables the addition of phosphate groups to significantly alter its stability and conformation, thereby allowing the transition toward a functionally active state</p>
<div id="fig-modeller-comparision" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-modeller-comparision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<img src=".\pics/Protein3/ModellerPics/Modeller_comparision_alltemplates.png" id="all-templates-grey" height="250" class="figure-img">
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-modeller-comparision-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: <strong>Structural quality assessment of the MoOsm1 homology model</strong>. <strong>A.</strong> Structural comparison of the MoOsm1 predicted model (dark green) against the structural templates (gray transparent structures). <strong>B.</strong> Structural comparison of the MoOsm1 predicted model (dark green) against the structural templates 2B9F, 3K3I, 3P5K, and 6RFP (gray transparent structures). <strong>C.</strong> Three-dimensional representation of the MoOsm1 monomer modeled via MODELLER using six experimental templates. The structure is color-coded by transferred B-factors, representing the thermal mobility and intrinsic flexibility inherited from the templates; cool tones (marine/lightteal) indicate the rigid catalytic core, while warm tones (yellow/orange) highlight the extreme flexibility of the activation loop (Thr171 region).
</figcaption>
</figure>
</div>
<p>PONER EN INGLES*** FIX ME</p>
<p><strong>Analizando el sitio TXY</strong> de las proteinas seleccionadas como homólogas, cuando este está presnete (todos menos rattus), se encuentra en regiones unmodeled. Problema a la hora de modelar pero el resto de la proteina se encontrara resuelta de manera correcta. Dada la similitud de secuencia y de funcion, consideramos correcto utilizar modeller como herramienta para el modelado por homología. (La zona de TXy será modelado con modelado de novo o ab initio mediante I-tasser)</p>
<p>¿Por qué NO es un análisis sesgado? El modelado por homología se basa en la premisa de que “estructura se conserva más que secuencia”. Si tu modelo se parece mucho a los templates en el “core” (el núcleo de la proteína), significa que Modeller ha hecho bien su trabajo de mantener la arquitectura plegada.</p>
<p>Lo que buscas: Que el esqueleto (backbone) coincida en las hélices alfa y láminas beta.</p>
<p>Donde esperas diferencias: En los loops (bucles). Si tu modelo es idéntico a los templates en los loops, ahí sí podría haber un sesgo (Modeller simplemente copió algo que quizás en tu proteína es distinto).</p>
</section>
<section id="interpretation-of-the-results-discussion" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-the-results-discussion">Interpretation of the results (Discussion)</h4>
<p>This graphical representation (<span class="citation" data-cites="just-Osm1-colored-modeller">@just-Osm1-colored-modeller</span>) confirms that the orange-colored regions identify a site of high intrinsic flexibility, a structural feature necessary to allow phosphorylation events that subsequently trigger conformational and stability changes. Consequently, the structural rigidity in this specific area is low, facilitating its functional transition</p>
<p>As visually demonstrated in the results (<span class="citation" data-cites="all-templates-grey">@all-templates-grey</span>), the structural similarity between the predicted MoOsm1 model and the templates 2B9F (<span class="math inline">\(RMSD = 0.811\)</span> Å; <span class="math inline">\(1,723/2,897\)</span> atoms), 3K3I (<span class="math inline">\(RMSD = 0.972\)</span> Å; <span class="math inline">\(1,908/2,897\)</span> atoms), 3P5K (<span class="math inline">\(RMSD = 1.113\)</span> Å; <span class="math inline">\(1,910/2,897\)</span> atoms), and 6RFP (<span class="math inline">\(RMSD = 0.759\)</span> Å; <span class="math inline">\(1,743/2,897\)</span> atoms) is notably higher (<span class="citation" data-cites="best-templates-grey">@best-templates-grey</span>) than the visual correspondence observed with 8H59 (<span class="math inline">\(RMSD = 0.930\)</span> Å; <span class="math inline">\(1,863/2,897\)</span> atoms) and 7W5C (<span class="math inline">\(RMSD = 1.023\)</span> Å; <span class="math inline">\(1,886/2,897\)</span> atoms).</p>
<p>It is important to note that the templates showing the highest visual similarity correspond to those with the best X-ray resolution and the highest sequence identity percentages, specifically 3P5K (<em>Mus musculus</em>) and 3K3I (<em>Homo sapiens</em>). Furthermore, these two structures possess a conserved TGY motif, providing a more biologically realistic framework than templates with a TXY site (specifically TEY) or those lacking the conserved motif (e.g., 6RFP).</p>
<p>Consequently, a refined modeling approach focusing on template 3K3I could be considered; although 3P5K also contains the conserved TGY motif, its higher RMSD (<span class="math inline">\(&gt; 1\)</span> Å) suggests a slightly lower global structural correspondence. Such a refinement would be expected to yield a lower average RMSD across templates and more realistic flexibility values. While the catalytic core remains highly conserved across all structures, the TGY site exhibits high flexibility. This mobility may either be an intrinsic requirement for protein activation or a result of using a diverse set of templates without a conserved TGY motif. Despite this, the global fold’s stability confirms the reliability of the current modeling process.</p>
<p>Such a refinement, by restricting the coordinates to a single high-resolution human template, would be expected to yield a more consistent local geometry and more realistic flexibility values. While the catalytic core remains highly conserved across all multi-template structures, the TGY site currently exhibits high flexibility (B-factor <span class="math inline">\(\approx 509\)</span>). This extreme mobility may either be an intrinsic requirement for protein activation or a structural bias introduced by using a diverse set of templates lacking the conserved TGY motif. Despite these local variations, the overall stability of the global fold confirms the reliability of the current modeling process.</p>
</section>
</section>
<section id="comparacion-i-tasser---modeller" class="level1">
<h1>COMPARACION i-TASSER - MODELLER</h1>
<p>The structural reliability of the MoHog1 models was corroborated through two independent computational approaches. On one hand, the I-TASSER prediction yielded a C-score of 0.90, which significantly exceeds the -1.5 threshold, indicating a high-confidence global fold with a high probability of correct topology. On the other hand, the Modeller homology modeling process produced a best-ranking model with a zDOPE score of -1.45. Since a zDOPE value below -1.0 is characteristic of native-like structures, the convergence of these two distinct metrics—one based on threading and the other on statistical potential energy—strongly supports the accuracy and stability of the generated 3D structures</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>